// the configured options and settings for amayhttps
#ifndef _HOME_AMAY_CODE_CPP_NETWORKING_AMAYHTTPS_AMAYNETCONFIG_H_IN
#define _HOME_AMAY_CODE_CPP_NETWORKING_AMAYHTTPS_AMAYNETCONFIG_H_IN

#define AMAYNET_VERSION_MAJOR 0
#define AMAYNET_VERSION_MINOR 1
#define AMAYNET_VERSION_PATCH 0

#endif
